config/routes.rb
NonProfit::Application.routes.draw do
  devise_for :users

  resources :companies do
    resources :charges
  end
  resources :users


  root to: 'welcome#index'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :presence => true
  has_many :donations
  has_many :users, through: :donations
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates :donation_amt, :presence => true
  belongs_to :user
  belongs_to :company


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :donations

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def create
    @account = Account.new(params[:account])
    if @account.save
    flash[:notice] = 'Account added'
    redirect account_path(@account)
    else
    render 'new'
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Set your secret key: remember to change this to your live secret key in production
    # See your keys here https://manage.stripe.com/account
    Stripe.api_key = ENV['secret_stripe_key']

    # Get the credit card details submitted by the form
    token = params[:stripeToken]
    amount = params[:amount].to_i * 100
    # Create the charge on Stripe's servers - this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        :amount => amount, # amount in cents, again
        :currency => "usd",
        :card => token,
        :description => params[:email]
      )
      if current_user
        user = current_user.id
      else
        user = nil
      end

      donation = Donation.create(:user_id => user, :company_id => params[:company_id], :donation_amt => (amount/100) )
      flash[:notice] = "Thank you for the donation"
      company = Company.find(params[:company_id])
      company.total_donation += amount/100
      company.save
      redirect_to company_path(donation.company_id)
    rescue Stripe::CardError => e
      # The card has been declined
    end
  end

private 


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies=Company.all
  end

  def new
    @company=Company.new
  end

  def create
    @company=Company.new(company_params)
    @company.total_donation = 0
    if @company.save
      
      flash[:notice] = 'Company added'
      redirect_to company_path(@company)
    else
      render 'new'
    end
  end

  def show
    @company=Company.find(params[:id])
  end

  def edit
    @company=Company.find(params[:id])
  end

  def update
    @company=Company.find(params[:id])
    if @company.update(company_params)
      flash[:notice] = 'Company updated.'
      redirect company_path(@company)
    else
      render 'new'
    end
  end

private
  def company_params
    params.require(:company).permit(:name, :short, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user=User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @companies=Company.all
    @company=Company.new
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/_donate_form.html.erb
  <form action="/companies/<%= "#{@company.id}" %>/charges/" method="POST" id="payment-form">
    <span class="payment-errors"></span>

    <div class="form-row">
      <label>
        <span>Email</span>
        <input type="text" name="email"/>
      </label>
    </div>
    <div class="form-row">
      <label>
        <span>Card Number</span>
        <input type="text" size="20" value="4242424242424242" data-stripe="number"/>
      </label>
    </div>
    <div class="form-row">
      <label>
        <span>CVC</span>
        <input type="text" size="4" value="434" data-stripe="cvc"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>Expiration (MM/YYYY)</span>
        <input type="text" size="2" value="04" data-stripe="exp-month"/>
      </label>
      <span> / </span>
      <input type="text" size="4" value="2016" data-stripe="exp-year"/>
    </div>

    <div class="form-row">
      <label>
        <span>Amount</span>
        <input type="text" size="8" name='amount' data-stripe="amount"/>
      </label>
    </div>

    <button type="submit">Submit Payment</button>
  </form>

app/views/companies/index.html.erb
<h1>All Companies</h1>
<ul>
  <% @companies.each do |company| %>
    <li><%= company.name %></li>
  <%end %>
</ul>

app/views/companies/new.html.erb
<h1>Add a Non Profit</h1>

<%= form_for @company do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   <div class="form-group">
    <%= f.label :short, "Provide a short one line description"%><br>
    <%= f.text_field :short %>
  </div>
   <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%= f.submit :class => 'btn btn-default' %>
<% end %>

app/views/companies/show.html.erb
<h1 class="company"><%= @company.name %> <small>Click to Donate!</small></h1>
<h4>Total Raised:  <%= number_to_currency(@company.total_donation) %></h4>
<%= @company.description %>

<hr>
<div class='col-md-6'>
<%= render '/charges/donate_form'%>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.company').click(function() {
    $('#payment-form').show()
    });
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NonProfit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    // This identifies your website in the createToken call below
    Stripe.setPublishableKey('pk_test_TSF1GBhZiUdpS3V40J20dDy6');

    var stripeResponseHandler = function(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and re-submit
        $form.get(0).submit();
      }
    };

    jQuery(function($) {
      $('#payment-form').submit(function(e) {
        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('button').prop('disabled', true);

        Stripe.card.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
      });
    });
  </script>
</head>
<body>
  <div class="navbar navbar-default">
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Donate", root_path %></li>
        <% if current_user %>
        <li><%= link_to "Your Past Donations", user_path(current_user) %></li>
        <li><%= link_to "Add Non-Profit", new_company_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% else %>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
        <% end %>
      </ul>
    </div>
  </div>
    <div class='container'>
  <%= flash[:notice] %>
  <%= flash[:error] %>
  <%= yield %>
    </div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>
  <h1>Please enter your contribution amount.</h1>
  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<h2> Welcome <%= @user.email %>, </h2>

<h4>Your Donations:</h4>
<ul>
  <% @user.donations.each do |donation| %>
    <li><%= Company.find(donation.company_id).name %> @ <%= number_to_currency(donation.donation_amt) %> on <%= donation.created_at.strftime("%m/%d/%Y") %> </li>
    <% end %>
</ul>

app/views/welcome/_company.html.erb
<div class="profile well col-md-2">
  <strong><%= link_to object.name, company_path(object)%></strong>
  <p><%= object.short %></p>
</div>

app/views/welcome/index.html.erb
<h1>Non-Profit Donation Center</h1>

<h4>Please visit a non-profit's page to donate</h4>
  <% @companies.each do |company| %>
    <%= render '/welcome/company', :object => company %>
  <% end %>


<div class='col-md-12'>
	<hr>
	<h5>Please Note: This site is for demostration purposes.  No donations will be made.</h5>
</div>